'use client';

import React from 'react';
import {
  Home,
  Car,
  ShoppingCart,
  ShoppingBag,
  Receipt,
  Utensils,
  Film,
  HeartPulse,
  GraduationCap,
  Briefcase,
  Plane,
  Gift,
  Phone,
  Wifi,
  Tv,
  Zap,
  ShieldAlert,
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  TrendingUp,
  Landmark,
  Fuel,
  Coffee,
  Sparkles,
  Tag,
  Folder,
  Package,
  Wrench,
  Baby,
  Dumbbell,
  Shirt,
  Bus,
  Flame,
  Droplets,
  DollarSign,
  Layers,
  Percent,
  LucideProps,
} from 'lucide-react';

export const CATEGORY_ICON_LIST = [
  { id: 'home', name: 'Ev & Konut', icon: Home },
  { id: 'car', name: 'Araç & Ulaşım', icon: Car },
  { id: 'fuel', name: 'Akaryakıt', icon: Fuel },
  { id: 'bus', name: 'Toplu Taşıma', icon: Bus },
  { id: 'shopping-cart', name: 'Market & Gıda', icon: ShoppingCart },
  { id: 'shopping-bag', name: 'Alışveriş', icon: ShoppingBag },
  { id: 'utensils', name: 'Yeme & İçme', icon: Utensils },
  { id: 'coffee', name: 'Kafe & İçecek', icon: Coffee },
  { id: 'receipt', name: 'Fatura & Vergi', icon: Receipt },
  { id: 'zap', name: 'Elektrik', icon: Zap },
  { id: 'flame', name: 'Doğalgaz', icon: Flame },
  { id: 'droplets', name: 'Su', icon: Droplets },
  { id: 'wifi', name: 'İnternet', icon: Wifi },
  { id: 'phone', name: 'Telekomünikasyon', icon: Phone },
  { id: 'tv', name: 'Dijital Abonelik', icon: Tv },
  { id: 'heart-pulse', name: 'Sağlık & Eczane', icon: HeartPulse },
  { id: 'graduation-cap', name: 'Eğitim & Kurs', icon: GraduationCap },
  { id: 'film', name: 'Eğlence & Sinema', icon: Film },
  { id: 'dumbbell', name: 'Spor & Fitness', icon: Dumbbell },
  { id: 'shirt', name: 'Giyim & Moda', icon: Shirt },
  { id: 'plane', name: 'Seyahat & Tatil', icon: Plane },
  { id: 'briefcase', name: 'İş & Meslek', icon: Briefcase },
  { id: 'gift', name: 'Hediye & Bağış', icon: Gift },
  { id: 'baby', name: 'Çocuk & Bebek', icon: Baby },
  { id: 'wrench', name: 'Bakım & Onarım', icon: Wrench },
  { id: 'banknote', name: 'Maaş & Gelir', icon: Banknote },
  { id: 'landmark', name: 'Banka & Finans', icon: Landmark },
  { id: 'credit-card', name: 'Kredi Kartı', icon: CreditCard },
  { id: 'wallet', name: 'Nakit & Cüzdan', icon: Wallet },
  { id: 'piggy-bank', name: 'Kumbara & Birikim', icon: PiggyBank },
  { id: 'trending-up', name: 'Yatırım & Hisse', icon: TrendingUp },
  { id: 'tag', name: 'Etiket / Genel', icon: Tag },
  { id: 'folder', name: 'Klasör / Diğer', icon: Folder },
];

const ICON_MAP: Record<string, React.FC<LucideProps>> = {
  home: Home,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  'shopping-cart': ShoppingCart,
  shoppingcart: ShoppingCart,
  'shopping-bag': ShoppingBag,
  shoppingbag: ShoppingBag,
  utensils: Utensils,
  coffee: Coffee,
  receipt: Receipt,
  zap: Zap,
  flame: Flame,
  droplets: Droplets,
  droplet: Droplets,
  wifi: Wifi,
  phone: Phone,
  tv: Tv,
  'heart-pulse': HeartPulse,
  heartpulse: HeartPulse,
  'graduation-cap': GraduationCap,
  graduationcap: GraduationCap,
  film: Film,
  dumbbell: Dumbbell,
  shirt: Shirt,
  plane: Plane,
  briefcase: Briefcase,
  gift: Gift,
  baby: Baby,
  wrench: Wrench,
  banknote: Banknote,
  landmark: Landmark,
  'credit-card': CreditCard,
  creditcard: CreditCard,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  piggybank: PiggyBank,
  'trending-up': TrendingUp,
  trendingup: TrendingUp,
  sparkles: Sparkles,
  tag: Tag,
  folder: Folder,
  package: Package,
  'shield-alert': ShieldAlert,
  dollarsign: DollarSign,
  layers: Layers,
  percent: Percent,
};

interface CategoryIconProps extends Omit<LucideProps, 'name'> {
  name?: string | null;
  fallbackIcon?: React.FC<LucideProps>;
}

export const CategoryIcon: React.FC<CategoryIconProps> = ({
  name,
  fallbackIcon: Fallback = Tag,
  ...props
}) => {
  if (!name) return <Fallback {...props} />;
  const normalizedKey = name.toLowerCase().replace(/\s+/g, '-');
  const IconComponent = ICON_MAP[normalizedKey] || Fallback;
  return <IconComponent {...props} />;
};
